import React from "react";

import type { IconProps } from "@radix-ui/react-icons/dist/types";

import {
    RiAddFill,
    RiAlignCenter,
    RiAlignJustify,
    RiAlignLeft,
    RiAlignRight,
    RiArrowDownSFill,
    RiArrowLeftSFill,
    RiArrowRightSFill,
    RiArrowUpCircleFill,
    RiAttachment2,
    RiBold,
    RiCheckFill,
    RiCheckboxBlankFill,
    RiCheckboxBlankLine,
    RiClipboardFill,
    RiCloseLine,
    RiCodeBlock,
    RiCodeSSlashFill,
    RiDeleteBin6Fill,
    RiDoubleQuotesL,
    RiEditFill,
    RiExternalLinkFill,
    RiFilmFill,
    RiH1,
    RiH2,
    RiH3,
    RiIndentDecrease,
    RiIndentIncrease,
    RiItalic,
    RiLineHeight,
    RiLink,
    RiLinkM,
    RiLinkUnlink,
    RiListOrdered,
    RiListOrdered2,
    RiListUnordered,
    RiMoonFill,
    RiMore2Fill,
    RiMoreFill,
    RiParagraph,
    RiStrikethrough,
    RiSubscript,
    RiSubtractFill,
    RiSuperscript,
    RiText,
    RiUnderline,
    RiUserSmileFill,
} from "@remixicon/react";

export const Icons = {
    add: RiAddFill,
    alignCenter: RiAlignCenter,
    alignJustify: RiAlignJustify,
    alignLeft: RiAlignLeft,
    alignRight: RiAlignRight,
    arrowDown: RiArrowDownSFill,
    arrowLeft: RiArrowLeftSFill,
    arrowRight: RiArrowRightSFill,
    attachment: RiAttachment2,
    blockquote: RiDoubleQuotesL,
    bold: RiBold,
    check: RiCheckFill,
    chevronDown: RiArrowDownSFill,
    chevronLeft: RiArrowLeftSFill,
    chevronRight: RiArrowRightSFill,
    chevronsUpDown: RiArrowUpCircleFill,
    clear: RiCloseLine,
    close: RiCloseLine,
    code: RiCodeSSlashFill,
    codeblock: RiCodeBlock,
    conflict: RiLinkUnlink,
    copy: RiClipboardFill,
    delete: RiDeleteBin6Fill,
    dependency: RiLinkM,
    editing: RiEditFill,
    ellipsis: RiMore2Fill,
    embed: RiFilmFill,
    emoji: RiUserSmileFill,
    externalLink: RiExternalLinkFill,
    h1: RiH1,
    h2: RiH2,
    h3: RiH3,
    hr: RiSubtractFill,
    image: Image,
    indent: RiIndentIncrease,
    italic: RiItalic,
    lineHeight: RiLineHeight,
    link: RiLink,
    media: Image,
    minus: RiSubtractFill,
    moon: RiMoonFill,
    more: RiMoreFill,
    moreVertical: RiMore2Fill,
    ol: RiListOrdered2,
    outdent: RiIndentDecrease,
    page: File,
    paragraph: RiParagraph,
    pragma: RiLink,
    strikethrough: RiStrikethrough,
    subscript: RiSubscript,
    superscript: RiSuperscript,
    text: RiText,
    todo: RiCheckboxBlankLine,
    trash: RiDeleteBin6Fill,
    twitter: (props: IconProps) => (
        <svg
            {...props}
            height="23"
            viewBox="0 0 1200 1227"
            width="23"
            xmlns="http://www.w3.org/2000/svg"
        >
            <path d="M714.163 519.284L1160.89 0H1055.03L667.137 450.887L357.328 0H0L468.492 681.821L0 1226.37H105.866L515.491 750.218L842.672 1226.37H1200L714.137 519.284H714.163ZM569.165 687.828L521.697 619.934L144.011 79.6944H306.615L611.412 515.685L658.88 583.579L1055.08 1150.3H892.476L569.165 687.854V687.828Z" />
        </svg>
    ),
    ul: RiListUnordered,
    underline: RiUnderline,
    unlink: RiLinkUnlink,
};